In [1]:
#linear algebra,vectors and matrix
import numpy as np

In [2]:
a= np.array([[10,15]])
b= np.array([[20,9]])
print(a)
print(b)
(a+b).T

[[10 15]]
[[20  9]]


array([[30],
       [24]])

In [3]:
a-b

array([[-10,   6]])

In [5]:
#scaler
a=2
u=np.array([[30,15]])
(a*u).T

array([[60],
       [30]])

In [7]:
#Dot product of 2 vectors
#For 2-d vectors, it is the equvalent to matrix multiication
u = np.array([10,20])
v = np.array([25,6])
print(10*25+20*6)
np.dot(u,v)

370


370

In [10]:
a = np.array([[12,10],[4,6],[40,31],])
b = np.array([[2,8],[46,63],[50,10],])
print(a, end="=a\n\n")
print(b, end="=b\n\n")


[[12 10]
 [ 4  6]
 [40 31]]=a

[[ 2  8]
 [46 63]
 [50 10]]=b



In [11]:
a+b

array([[14, 18],
       [50, 69],
       [90, 41]])

In [12]:
a-b

array([[ 10,   2],
       [-42, -57],
       [-10,  21]])

In [13]:
#Matrix scalar multification
a=4
b=np.array([[2,5],[3,7],[8,6],])
a*b

array([[ 8, 20],
       [12, 28],
       [32, 24]])

In [14]:
#Matrix and vector multification
a=[[5,10],[15,20]]
b=[10,12]
np.dot(a,b)

array([170, 390])

In [15]:
#Matrix to Matrix multification
a = [[5,10],[15,20],[25,30]]
b = [[3,6],[9,5]]
np.dot(a,b)

array([[105,  80],
       [225, 190],
       [345, 300]])

In [18]:
#Transpose a matrix
a =np.array([[5,10],[15,20],[25,30]])
print(a, end="=a\n\n")
print(a.T, end="=aT")

[[ 5 10]
 [15 20]
 [25 30]]=a

[[ 5 15 25]
 [10 20 30]]=aT

In [19]:
#Create an Identity matrix
I1 = np.eye(2)
I2 = np.eye(3)
print(I1, end=" = I1\n\n")
print(I2, end=" = I2\n\n")

[[1. 0.]
 [0. 1.]] = I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I2



In [20]:
#Inverse a matrix
#Given a square matrix a
# return the matrix ainv satisfying dot(a, ainv)
# = dot(ainv,a)= eye(a.shape[0]).
a = np.array([
    [2,1,0],
    [0,1,0],
    [1,2,2],
])
print(a, end=" =a\n\n")
print(np.linalg.inv(a), end="=|a|")

[[2 1 0]
 [0 1 0]
 [1 2 2]] =a

[[ 0.5  -0.5   0.  ]
 [ 0.    1.    0.  ]
 [-0.25 -0.75  0.5 ]]=|a|